[package]
name = "rel"
version = "0.1.0"
authors = ["alex <alex8224@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = {version = "1.0.72", feature = "full"}
quote = "*"

[lib]
proc-macro = true